# Generated by Django 3.2 on 2023-07-03 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200506_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qqlogintokenmodel',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
